version: '3.7'
services:
  app:
    build: .
    command: sh -c "npm start"
    ports:
      - "4200:4200"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules  # Ensuring node_modules isn't overridden
    environment:
      - CHOKIDAR_USEPOLLING=true  # Helps with file watching inside Docker
    networks:
      - mynetwork
networks:
  mynetwork:
